# Font Configuration
font_size 16.0
font_family JetBrains Mono Nerd Font

# Window Configuration
window_padding_width 0 10
background_opacity 0.80
#background_blur 1
hide_window_decorations yes

# Cursor Configuration
cursor_shape block
cursor_blink_interval 1

# Scrollback
scrollback_lines 3000

# Terminal features
copy_on_select yes
strip_trailing_spaces smart

# Key bindings for common actions
map ctrl+shift+n new_window
map ctrl+t new_tab
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Shell integration
shell_integration enabled


confirm_os_window_close 0

#colors
color0 #45475a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 #94e2d5
color7 #a6adc8
color8 #585b70
color9 #f37799
color10 #89d88b
color11 #ebd391
color12 #74a8fc
color13 #f2aede
color14 #6bd7ca
color15 #bac2de

cursor                #f5e0dc
cursor_text_color     #1e1e2e
background            #1e1e2e
foreground            #cdd6f4
selection_foreground  #cdd6f4
selection_background  #585b70
active_border_color   #b4befe
inactive_border_color #313244
url_color             #b4befe

active_tab_foreground   #11111b
active_tab_background   #b4befe
inactive_tab_foreground #a3b4eb
inactive_tab_background #313244
cursor_trail_color      #a3b4eb
